extern const char * index_html = "<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<style>"
"#birdPhoto{"
"  height: calc(100vh - 64px);"
"}"
"body {"
"margin: 0;"
"text-align: center;"
"}"
"header {"
"display: flex;"
"gap: 20px;"
"align-items: center;"
"background: hsl(224, 73%, 80%);"
"padding: 0 30px;"
"}"
".spacer {"
"flex: 1 1 auto;"
"}"
".pie {"
"--p: 20;"
"--b: 20px;"
"--w: 60px;"
"--c: #337AB7;"
"--f: #eee;"
"cursor: pointer;"
"width: var(--w);"
"aspect-ratio: 1;"
"position: relative;"
"display: inline-grid;"
"margin: 5px;"
"place-content: center;"
"font-size: 15px;"
"font-weight: bold;"
"font-family: sans-serif;"
"}"
".pie:before,"
".pie:after {"
"content: \"\";"
"position: absolute;"
"border-radius: 50%;"
"}"
".pie:before {"
"inset: 0;"
"background: radial-gradient(farthest-side, var(--c) 98%, #0000) top/var(--b) var(--b) no-repeat, conic-gradient(var(--c) calc(var(--p) * 1%), var(--f) 0);"
"mask: radial-gradient(farthest-side, #0000 calc(99% - var(--b)), #000 calc(100% - var(--b)));"
"}"
".pie:after {"
"inset: calc(50% - var(--b) / 2);"
"background: var(--c);"
"transform: rotate(calc(var(--p) * 3.6deg)) translateY(calc(50% - var(--w) / 2));"
"}"
".no-round:before {"
"background-size: 0 0, auto;"
"}"
".no-round:after {"
"content: none;"
"}"
"[data-title] {"
"position: relative;"
"cursor: help;"
"}"
"[data-title]::after {"
"display: block;"
"transform: rotate(0) translateY(0);"
"font-size: 16px;"
"font-weight: lighter;"
"font-family: 'Times New Roman', Times, serif;"
"border-radius: 0;"
"width: 200%;"
"content: attr(data-title);"
"position: absolute;"
"left: 0;"
"top: 2em;"
"opacity: 0;"
"transition: 0.5s;"
"pointer-events: none;"
"background: rgba(201, 213, 223, 0.9);"
"color: #4e4e4e;"
"}"
"[data-title]:hover::after {"
"opacity: 1;"
"}"
"[data-title_pie]::after {"
"left: unset;"
"top: 4em;"
"height: 4.5em;"
"}"
"</style>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Document</title>"
"<link rel=\"stylesheet\""
"href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />"
"</head>"
"<body>"
"<header>"
"<button id=\"takePhoto\" data-title=\"click to take a photo\" onclick=\"capturePhoto();\">"
"<span class=\"material-symbols-outlined\">photo_camera</span>"
"</button>"
"<button id=\"downloadPhoto\" data-title=\"click to save photo\" onclick=\"savePhoto();\">"
"<span class=\"material-symbols-outlined\">download</span>"
"</button>"
"<div><span id=\"birdCounter\"></span> birds have allready feeded</div>"
"<div class=\"spacer\"></div>"
"<div>Last update was at <span id=\"lastUpdate\"></span></div>"
"<div onclick=\"checkFood();\" data-title_pie"
"data-title=\"Information about the feed in the feeder. click to update\" class='pie' id=\"foodLevel\""
"style=\"--p:85;--b:10px;--c:#ff891b\">85%</div>"
"</header>"
"<main>"
"<img src=\"saved-photo\" id=\"birdPhoto\" width=\"70%\">"
"</main>"
"</body>"
"<script>"
"var birdNum = -1;"
"var birdPhoto = document.getElementById(\"birdPhoto\");"
"var takePhoto = document.getElementById(\"takePhoto\");"
"var downloadPhoto = document.getElementById(\"downloadPhoto\");"
"var foodLevel = document.getElementById(\"foodLevel\");"
"var lastUpdate = document.getElementById(\"lastUpdate\");"
"var birdCounter = document.getElementById(\"birdCounter\");"
"function capturePhoto() {"
"var xhr = new XMLHttpRequest();"
"xhr.open('GET', \"/capture\", true);"
"xhr.send();"
"clearInterval(time);"
"setTimeout(() => {"
"birdPhoto.src = \"saved-photo\"+\"?\"+Date.now(); time = setInterval(birdCheck, 5000);"
"takePhoto.removeAttribute('disabled');"
"downloadPhoto.removeAttribute('disabled');"
"}, 5000);"
"takePhoto.setAttribute('disabled', 1);"
"downloadPhoto.setAttribute('disabled', 1);"
"}"
"function checkFood() {"
"var xhr = new XMLHttpRequest();"
"xhr.open('GET', \"/food-level\", true);"
"xhr.send();"
"xhr.onload = () => {"
"foodLevel.innerText = xhr.response + \"%\";"
"foodLevel.style.setProperty(\"--p\", xhr.response);"
"let date = new Date();"
"lastUpdate.innerText = date.toLocaleString("");"
"}"
"}"
"function birdCheck() {"
"var xhr = new XMLHttpRequest();"
"xhr.open('GET', \"/bird-check\", true);"
"xhr.send();"
"xhr.onload = () => {"
"if (birdNum == -1) { birdNum = xhr.response; }"
"if (xhr.response != birdNum) {"
"birdNum = xhr.response;"
"birdPhoto.src = \"saved-photo\"+\"?\"+Date.now();"
"}"
"birdCounter.innerText = birdNum;"
"}"
"}"
"function savePhoto() {"
"const a = document.createElement('a');"
"a.setAttribute('href', 'saved-photo');"
"a.setAttribute('target', '_blank');"
"document.body.appendChild(a);"
"a.click();"
"}"
"birdCheck();"
"var time = setInterval(birdCheck, 5000);"
"checkFood();"
"setInterval(checkFood, 1200000);"
"</script>"
"</html>"
"";